name: LatentImportanceSampling
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - scikit-learn
  - tqdm
  - yaml
  - pip:
    - cvxpy
    - nflows
    - prdc
